[[redirects]]
  from   = "/stats/*"
  to     = "https://plausible.io/:splat"
  status = 200
  force  = true
  
[[redirects]]
  from   = "/plausible/*"
  to     = "https://plausible.io/:splat"
  status = 200
  force  = true

[[redirects]]
from   = "/api/event"
to     = "https://plausible.io/api/event"
status = 200
force  = true

[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

[build]
  command = "npm run build && npm run build:docs"
  publish = "netlify-dist"

[[plugins]]
  package = "@netlify/plugin-copy-files"
  [plugins.inputs]
    from = "build"
    to   = "netlify-dist"

[[plugins]]
  package = "@netlify/plugin-copy-files"
  [plugins.inputs]
    from = "blog/dist"
    to   = "netlify-dist/blog" 
