[[redirects]]
  from   = "/stats/*"
  to     = "https://plausible.io/:splat"
  status = 200
  force  = true

[[redirects]]
  from   = "/plausible/*"
  to     = "https://plausible.io/:splat"
  status = 200
  force  = true

[[redirects]]
from   = "/api/event"
to     = "https://plausible.io/api/event"
status = 200
force  = true

[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

[build]
  command = """
    npm run build && \
    npm run build:docs && \
    rm -rf netlify-dist && mkdir -p netlify-dist && \
    cp -r build/*       netlify-dist/          && \
    cp -r docs/dist     netlify-dist/docs
  """
  publish = "netlify-dist"
